#' Differential Summary Utilities
#' @description Helper plotting functions used in the DE summary panel, including volcano and MA plot utilities and rescaling helpers.
#' @details These functions are intended for internal use by the Shiny UI and are documented to ease future package extraction.
#' @keywords internal

#' Create a volcano plot visualising differential expression (DE) results
#' @description This function creates a volcano plot to visualise the results
#' of a DE analysis.
#' @param peaks.de.results the table of DE peaks, usually generated by
#' \code{\link{de_analysis}}
#' @param pval.threshold,lfc.threshold the p-value and/or log2(fold-change)
#' thresholds to determine whether a peak is DE
#' @param alpha the transparency of points; ignored for DE peaks if
#' add.expression.colour.gradient is TRUE; default is 0.1
#' @param xlims a single value to create (symmetric) x-axis limits; by default
#' inferred from the data
#' @param log10pval.cap whether to cap the log10(p-value at -10); any p-values
#' lower that 10^(-10) are set to the cap for plotting
#' @param add.colours whether to colour peaks based on their log2(fold-change)
#' and -log10(p-value); default is TRUE
#' @param add.expression.colour.gradient whether to add a colour gradient
#' for DE peaks to present their log2(expression); default is TRUE
#' @param add.guide.lines whether to add vertical and horizontal guide lines
#' to the plot to highlight the thresholds; default is TRUE
#' @param add.labels.auto whether to automatically label peaks with the
#' highest |log2(fold-change)| and expression; default is TRUE
#' @param add.labels.custom whether to add labels to user-specified peaks;
#' the parameter peaks.to.label must also be specified; default is FALSE
#' @param ... parameters passed on to \code{\link{volcano_enhance}}
#' @return The volcano plot as a ggplot object.
#' @export
volcano_plot <- function(
    peaks.de.results,
    pval.threshold = 0.05,
    lfc.threshold = 1,
    alpha = 0.1,
    xlims = NULL,
    log10pval.cap = TRUE,
    add.colours = TRUE,
    add.expression.colour.gradient = TRUE,
    add.guide.lines = TRUE,
    add.labels.auto = TRUE,
    add.labels.custom = FALSE,
    ...
){
  df = peaks.de.results |>
    dplyr::mutate(peak = .data$m_z, log10pval = log10(.data$pvalAdj), name = stringr::str_wrap(.data$display_name)) |>
    dplyr::filter(!is.na(.data$log10pval))

  if(all(df$log10pval >= -10)) log10pval.cap <- FALSE
  if(log10pval.cap) df$log10pval[df$log10pval < -10] <- -10

  lfc <- NULL; log10pval <- NULL
  vp <- ggplot2::ggplot(data = df, mapping = ggplot2::aes(x = .data$lfc, y = -.data$log10pval,label=.data$name)) +
    ggplot2::theme_minimal() +
    ggplot2::xlab("log2(FC)") +
    ggplot2::ylab("-log10(pval)")

  if(is.null(xlims)){
    max.abs.lfc = max(abs(df[df$log10pval > -Inf,]$lfc))
    vp <- vp + ggplot2::xlim(-max.abs.lfc, max.abs.lfc)
  }else{
    vp <- vp + ggplot2::xlim(-abs(xlims), abs(xlims))
  }

  if(log10pval.cap){
    vp <- vp + ggplot2::scale_y_continuous(labels=c("0.0", "2.5", "5.0", "7.5", ">10"))
  }

  if(any(add.colours,
         add.expression.colour.gradient,
         add.guide.lines,
         add.labels.auto,
         add.labels.custom)){
    vp <- volcano_enhance(
      vp = vp,
      df = df,
      pval.threshold = pval.threshold,
      lfc.threshold = lfc.threshold,
      alpha = alpha,
      add.colours = add.colours,
      add.expression.colour.gradient = add.expression.colour.gradient,
      add.guide.lines = add.guide.lines,
      add.labels.auto = add.labels.auto,
      add.labels.custom = add.labels.custom,
      ...
    )
  }

  return(vp)

}

#' @description \code{\link{volcano_enhance}} is called indirectly by
#' \code{\link{volcano_plot}} to add extra features.
#' @param vp volcano plot as a ggplot object (usually passed by \code{\link{volcano_plot}})
#' @param df data frame of DE results for all peaks (usually passed by
#' \code{\link{volcano_plot}})
#' @param point.colours a vector of 4 colours to colour peaks with both pval
#' and lfc under thresholds, just pval under threshold, just lfc under threshold,
#' both pval and lfc over threshold (DE peaks) respectively; only used if
#' add.colours is TRUE
#' @param raster whether to rasterize non-DE peaks with ggraster to reduce
#' memory usage; particularly useful when saving plots to files
#' @param colour.gradient.scale a vector of two colours to create a colour
#' gradient for colouring the DE peaks based on expression; a named list with
#' components left and right can be supplied to use two different colour scales;
#' only used if add.expression.colour.gradient is TRUE
#' @param colour.gradient.breaks,colour.gradient.limits parameters to customise
#' the legend of the colour gradient scale; especially useful if creating
#' multiple plots or a plot with two scales;
#' only used if add.expression.colour.gradient is TRUE
#' @param guide.line.colours a vector with two colours to be used to colour
#' the guide lines; the first colour is used for the p-value and log2(fold-change)
#' thresholds and the second for double those values
#' @param annotation annotation data frame containing a match between the peak
#' field of df (usually ENSEMBL IDs) and the peak names that should be shown
#' in the plot labels; not necessary if df already contains peak names
#' @param n.labels.auto a integer vector of length 3 denoting the number of
#' peaks that should be automatically labelled; the first entry corresponds to
#' DE peaks with the lowest p-value, the second to those with highest absolute
#' log2(fold-change) and the third to those with highest expression; a single
#' integer can also be specified, to be used for all 3 entries; default is 5
#' @param peaks.to.label a vector of peak names to be labelled in the
#' plot; if names are present those are shown as the labels (but the values are
#' the ones matched - this is to allow custom peak names to be presented)
#' @param seed the random seed to be used for reproducibility; only used for
#' ggrepel::geom_label_repel if labels are present
#' @param label.force passed to the force argument of ggrepel::geom_label_repel;
#' higher values make labels overlap less (at the cost of them being further
#' away from the points they are labelling)
#' @return The enhanced volcano plot as a ggplot object.
#' @export
#' @rdname volcano_plot
volcano_enhance <- function(
    vp,
    df,
    pval.threshold,
    lfc.threshold,
    alpha,
    add.colours,
    point.colours = c("#bfbfbf", "orange", "red", "blue"),
    raster = FALSE,
    add.expression.colour.gradient,
    colour.gradient.scale = list(left  = c("#99e6ff", "#000066"),
                                 right = c("#99e6ff", "#000066")),
    colour.gradient.breaks = ggplot2::waiver(),
    colour.gradient.limits = NULL,
    add.guide.lines,
    guide.line.colours = c("green", "blue"),
    add.labels.auto,
    add.labels.custom,
    annotation = NULL,
    n.labels.auto = c(5, 5, 5),
    peaks.to.label = NULL,
    seed = 0,
    label.force = 1
){

  logp.threshold = log10(pval.threshold)

  if(add.colours){
    colours = vector(length=nrow(df))
    colours[] = point.colours[1]
    colours[abs(df$lfc) > lfc.threshold] = point.colours[2]
    colours[df$log10pval < logp.threshold] = point.colours[3]
    colours[abs(df$lfc) > lfc.threshold & df$log10pval < logp.threshold] = point.colours[4]
    df$colours <- colours

    if(raster){
      vp <- vp + ggrastr::rasterise(ggplot2::geom_point(alpha = alpha, colour = colours))
    }else{
      vp <- vp + ggplot2::geom_point(alpha = alpha, colour = colours, fill = colours)
    }
  }

  if(add.expression.colour.gradient){
    df.colour.gradient <- df |>
      dplyr::filter(abs(.data$lfc) > lfc.threshold & .data$log10pval < logp.threshold) |>
      dplyr::arrange(.data$log2_intensity)
    if(identical(colour.gradient.scale$left, colour.gradient.scale$right)){
      vp <- vp +
        ggplot2::geom_point(data = df.colour.gradient,
                   mapping = ggplot2::aes(x = .data$lfc, y = -.data$log10pval, colour = .data$log2_intensity)) +
        ggplot2::scale_color_gradient(low = colour.gradient.scale$left[1],
                             high = colour.gradient.scale$left[2],
                             breaks = colour.gradient.breaks,
                             limits = colour.gradient.limits) +
        ggplot2::labs(colour = "log2(intensity)")
    }else{
      vp <- vp +
        ggplot2::geom_point(data = dplyr::filter(df.colour.gradient, .data$lfc < 0),
                   mapping = ggplot2::aes(x = .data$lfc, y = -.data$log10pval, colour = .data$log2_intensity)) +
        ggplot2::scale_color_gradient(low = colour.gradient.scale$left[1],
                             high = colour.gradient.scale$left[2],
                             breaks = colour.gradient.breaks,
                             limits = colour.gradient.limits) +
        ggplot2::labs(colour = "log2(intensity)") +
        ggnewscale::new_scale_colour() +
        ggplot2::geom_point(data = dplyr::filter(df.colour.gradient, .data$lfc > 0),
                   mapping = ggplot2::aes(x = .data$lfc, y = -.data$log10pval, colour = .data$log2_intensity)) +
        ggplot2::scale_colour_gradient(low = colour.gradient.scale$right[1],
                              high = colour.gradient.scale$right[2],
                              breaks = colour.gradient.breaks,
                              limits = colour.gradient.limits) +
        ggplot2::labs(colour = "log2(intensity)")
    }
  }

  if(add.guide.lines){
    vp <- vp +
      ggplot2::geom_vline(xintercept = lfc.threshold,  colour = guide.line.colours[1]) +
      ggplot2::geom_vline(xintercept = -lfc.threshold,  colour = guide.line.colours[1]) +
      ggplot2::geom_vline(xintercept =  2 * lfc.threshold,  colour = guide.line.colours[2]) +
      ggplot2::geom_vline(xintercept = -2 * lfc.threshold,  colour = guide.line.colours[2]) +
      ggplot2::geom_hline(yintercept = -logp.threshold, colour = guide.line.colours[1]) +
      ggplot2::geom_hline(yintercept = -2 * logp.threshold, colour = guide.line.colours[2])
  }

  if(add.labels.auto | add.labels.custom){
    if(!is.null(annotation)){
      df <- df |>
        dplyr::mutate(
          symbol = .data$peak,
          name = ifelse(is.na(.data$symbol), .data$peak, .data$symbol)
        ) |>
        dplyr::select(-.data$symbol)
    }else{
      df <- df |> dplyr::mutate(name = .data$peak)
    }

    df.label <- tibble::tibble()
    if(add.labels.custom){
      peaks.to.rename <- peaks.to.label[names(peaks.to.label) != ""]
      peaks.to.label <- df$name[(match(peaks.to.label, c(df$name, df$peak)) - 1) %% nrow(df) + 1]
      peaks.to.label <- unique(peaks.to.label[!is.na(peaks.to.label)])
      peaks.to.rename <- peaks.to.rename[peaks.to.rename %in% peaks.to.label]
      df.label <- dplyr::filter(df, .data$name %in% peaks.to.label)
      df.label$name[match(peaks.to.rename, df.label$name)] <- names(peaks.to.rename)
      if(nrow(df.label) == 0){
        message(paste0("add.labels.custom was TRUE but no peaks specified; ",
                       "did you forget to supply peaks.to.label or annotation?"))
      }
    }

    if(add.labels.auto){
      if(length(n.labels.auto) == 1) n.labels.auto <- rep(n.labels.auto, 3)
      df.significant <- dplyr::filter(df, !(.data$name %in% peaks.to.label))

      df.significant <- df.significant[order(abs(df.significant$lfc), decreasing=TRUE), ]
      df.highest.lfc <- utils::head(df.significant, n.labels.auto[1])
      df.rest <- utils::tail(df.significant, nrow(df.significant) - n.labels.auto[1]) |>
        dplyr::filter(abs(.data$lfc) > lfc.threshold, .data$log10pval < logp.threshold)

      df.rest <- df.rest[order(abs(df.rest$log10pval), decreasing=TRUE), ]
      df.lowest.p.vals <- utils::head(df.rest, n.labels.auto[2])
      df.rest <- utils::tail(df.rest, nrow(df.rest) - n.labels.auto[2])

      df.rest <- df.rest[order(df.rest$log2_intensity, decreasing=TRUE), ]
      df.highest.abn <- utils::head(df.rest, n.labels.auto[3])

      df.label <- rbind(df.lowest.p.vals, df.highest.lfc, df.highest.abn, df.label) |>
        dplyr::distinct(.data$name, .keep_all = TRUE)
    }

    set.seed(seed = seed)
    # vp <- vp +
    #   ggrepel::geom_label_repel(
    #     data = df.label,
    #     mapping = aes(x = .data$lfc, y = -.data$log10pval, label = .data$name),
    #     max.overlaps = Inf,
    #     force = label.force,
    #     point.size = NA
    #   )
  }

  return(vp)

}

#' Create an MA plot visualising differential expression (DE) results
#' @description This function creates an MA plot to visualise the results
#' of a DE analysis.
#' @inheritParams volcano_plot
#' @param ylims a single value to create (symmetric) y-axis limits; by default
#' inferred from the data
#' @param ... parameters passed on to \code{\link{ma_enhance}}
#' @return The MA plot as a ggplot object.
#' @export
ma_plot <- function(
    peaks.de.results,
    pval.threshold = 0.05,
    lfc.threshold = 1,
    alpha = 0.1,
    ylims = NULL,
    add.colours = TRUE,
    add.expression.colour.gradient = TRUE,
    add.guide.lines = TRUE,
    add.labels.auto = TRUE,
    add.labels.custom = FALSE,
    ...
){
  df = peaks.de.results |>
    dplyr::mutate(peak = .data$m_z, log10pval = log10(.data$pvalAdj), name = stringr::str_wrap(.data$display_name)) |>
    dplyr::filter(!is.na(.data$log10pval))
  log2_intensity <- NULL; lfc <- NULL
  p <- ggplot2::ggplot(data = df, mapping = ggplot2::aes(x = .data$log2_intensity, y = .data$lfc,label=.data$name)) +
    ggplot2::theme_minimal() +
    ggplot2::xlab("Average log2(intensity)") +
    ggplot2::ylab("log2(FC)")

  if(is.null(ylims)){
    max.abs.lfc = max(abs(df$lfc))
    p <- p + ggplot2::ylim(-max.abs.lfc, max.abs.lfc)
  }else{
    p <- p + ggplot2::ylim(-abs(ylims), abs(ylims))
  }

  if(any(add.colours,
         add.expression.colour.gradient,
         add.guide.lines,
         add.labels.auto,
         add.labels.custom)){
    p <- ma_enhance(
      p = p,
      df = df,
      pval.threshold = pval.threshold,
      lfc.threshold = lfc.threshold,
      alpha = alpha,
      add.colours = add.colours,
      add.expression.colour.gradient = add.expression.colour.gradient,
      add.guide.lines = add.guide.lines,
      add.labels.auto = add.labels.auto,
      add.labels.custom = add.labels.custom,
      ...
    )
  }

  return(p)

}

#' Add features to an MA plot visualising differential expression (DE) results
#' @description \code{\link{ma_enhance}} is called indirectly by
#' \code{\link{ma_plot}} to add extra features.
#' @param p MA plot as a ggplot object (usually passed by \code{\link{ma_plot}})
#' @param df data frame of DE results for all peaks (usually passed by
#' \code{\link{ma_plot}})
#' @return The enhanced MA plot as a ggplot object.
#' @export
#' @rdname ma_plot
ma_enhance <- function(
    p,
    df,
    pval.threshold,
    lfc.threshold,
    alpha,
    add.colours,
    point.colours = c("#bfbfbf", "orange", "red", "blue"),
    raster = FALSE,
    add.expression.colour.gradient,
    colour.gradient.scale = list(left  = c("#99e6ff", "#000066"),
                                 right = c("#99e6ff", "#000066")),
    colour.gradient.breaks = ggplot2::waiver(),
    colour.gradient.limits = NULL,
    add.guide.lines,
    guide.line.colours = c("green", "blue"),
    add.labels.auto,
    add.labels.custom,
    annotation = NULL,
    n.labels.auto = c(5, 5, 5),
    peaks.to.label = NULL,
    seed = 0,
    label.force = 1
){

  logp.threshold = log10(pval.threshold)

  if(add.colours){
    colours = vector(length=nrow(df))
    colours[] = point.colours[1]
    colours[abs(df$lfc) > lfc.threshold] = point.colours[2]
    colours[df$log10pval < logp.threshold] = point.colours[3]
    colours[abs(df$lfc) > lfc.threshold & df$log10pval < logp.threshold] = point.colours[4]
    df$colours <- colours

    if(raster){
      p <- p + ggrastr::rasterise(ggplot2::geom_point(alpha = alpha, colour = colours))
    }else{
      p <- p + ggplot2::geom_point(alpha = alpha, colour = colours, fill = colours)
    }
  }

  if(add.expression.colour.gradient){
    df.colour.gradient <- df |>
      dplyr::filter(abs(.data$lfc) > lfc.threshold & .data$log10pval < logp.threshold) |>
      dplyr::arrange(.data$log2_intensity)
    if(identical(colour.gradient.scale$left, colour.gradient.scale$right)){
      p <- p +
        ggplot2::geom_point(data = df.colour.gradient,
                   mapping = ggplot2::aes(x = .data$log2_intensity, y = .data$lfc, colour = .data$log2_intensity)) +
        ggplot2::scale_color_gradient(low = colour.gradient.scale$left[1],
                             high = colour.gradient.scale$left[2],
                             breaks = colour.gradient.breaks,
                             limits = colour.gradient.limits) +
        ggplot2::labs(colour = "log2(intensity)")
    }else{
      p <- p +
        ggplot2::geom_point(data = dplyr::filter(df.colour.gradient, .data$lfc < 0),
                   mapping = ggplot2::aes(x = .data$log2_intensity, y = .data$lfc, colour = .data$log2_intensity)) +
        ggplot2::scale_color_gradient(low = colour.gradient.scale$left[1],
                             high = colour.gradient.scale$left[2],
                             breaks = colour.gradient.breaks,
                             limits = colour.gradient.limits) +
        ggplot2::labs(colour = "log2(intensity)") +
        ggnewscale::new_scale_colour() +
        ggplot2::geom_point(data = dplyr::filter(df.colour.gradient, .data$lfc > 0),
                   mapping = ggplot2::aes(x = .data$log2_intensity, y = .data$lfc, colour = .data$log2_intensity)) +
        ggplot2::scale_colour_gradient(low = colour.gradient.scale$right[1],
                              high = colour.gradient.scale$right[2],
                              breaks = colour.gradient.breaks,
                              limits = colour.gradient.limits) +
        ggplot2::labs(colour = "log2(intensity)")
    }
  }

  if(add.guide.lines){
    p <- p +
      ggplot2::geom_hline(yintercept =      lfc.threshold,  colour = guide.line.colours[1]) +
      ggplot2::geom_hline(yintercept =     -lfc.threshold,  colour = guide.line.colours[1]) +
      ggplot2::geom_hline(yintercept =  2 * lfc.threshold,  colour = guide.line.colours[2]) +
      ggplot2::geom_hline(yintercept = -2 * lfc.threshold,  colour = guide.line.colours[2])
  }

  if(add.labels.auto | add.labels.custom){
    if(!is.null(annotation)){
      df <- df |>
        dplyr::mutate(
          symbol = .data$peak,
          name = ifelse(is.na(.data$symbol), .data$peak, .data$symbol)
        ) |>
        dplyr::select(-.data$symbol)
    }else{
      df <- df |> dplyr::mutate(name = .data$peak)
    }

    df.label <- tibble::tibble()
    if(add.labels.custom){
      peaks.to.rename <- peaks.to.label[names(peaks.to.label) != ""]
      peaks.to.label <- df$name[(match(peaks.to.label, c(df$name, df$peak)) - 1) %% nrow(df) + 1]
      peaks.to.label <- unique(peaks.to.label[!is.na(peaks.to.label)])
      peaks.to.rename <- peaks.to.rename[peaks.to.rename %in% peaks.to.label]
      df.label <- dplyr::filter(df, .data$name %in% peaks.to.label)
      df.label$name[match(peaks.to.rename, df.label$name)] <- names(peaks.to.rename)
      if(nrow(df.label) == 0){
        message(paste0("add.labels.custom was TRUE but no peaks specified; ",
                       "did you forget to supply peaks.to.label or annotation?"))
      }
    }

    if(add.labels.auto){
      if(length(n.labels.auto) == 1) n.labels.auto <- rep(n.labels.auto, 3)
      df.significant <- dplyr::filter(df, !(.data$name %in% peaks.to.label))
      df.significant <- df.significant[order(abs(df.significant$lfc), decreasing=TRUE), ]
      df.highest.lfc <- utils::head(df.significant, n.labels.auto[1])
      df.rest <- utils::tail(df.significant, nrow(df.significant) - n.labels.auto[1]) |>
        dplyr::filter(abs(.data$lfc) > lfc.threshold, .data$log10pval < logp.threshold)

      df.rest <- df.rest[order(abs(df.rest$log10pval), decreasing=TRUE), ]
      df.lowest.p.vals <- utils::head(df.rest, n.labels.auto[2])
      df.rest <- utils::tail(df.rest, nrow(df.rest) - n.labels.auto[2])

      df.rest <- df.rest[order(df.rest$log2_intensity, decreasing=TRUE), ]
      df.highest.abn <- utils::head(df.rest, n.labels.auto[3])

      df.label <- rbind(df.lowest.p.vals, df.highest.lfc, df.highest.abn, df.label) |>
        dplyr::distinct(.data$name, .keep_all = TRUE)
    }

    set.seed(seed = seed)
    # p <- p +
    #   ggrepel::geom_label_repel(
    #     data = df.label,
    #     mapping = aes(x = .data$log2_intensity, y = .data$lfc, label = .data$name),
    #     max.overlaps = Inf,
    #     force = label.force,
    #     point.size = NA
    #   )
  }
  return(p)
}


rescale_matrix <- function(
    mat,
    type = c('Intensity', 'Log2 Intensity', 'Mean Scaled', 'Z-score')
){
  type <- type [1]
  if(type == 'Intensity'){
    mat <- mat
  }else if(type == 'Log2 Intensity'){
    mat <- log2(mat + 1)
  }else if(type == 'Mean Scaled'){
    mat <- mat / rowMeans(mat)
  }else if(type == 'Z-score'){
    mat <- t(scale(t(mat)))
  }
  mat
}
