#' Generate the DE summary panel of the shiny app
#' @description These are the UI and server components of the Heatmap panel of the
#' shiny app. It is generated by including 'DEsummary' in the panels.default argument
#' of \code{\link{generateShinyApp}}.
#' @inheritParams DEpanel
#' @inheritParams DEplotPanel
#' @return The UI and Server components of the shiny module, that can be used
#' within the UI and Server definitions of a shiny app.
#' @name DEsummaryPanel
NULL

#' @rdname DEsummaryPanel
#' @export
BulkORAPanelUI <- function(id, bulk.metadata, show = TRUE){
  ns <- NS(id)
  
  if(show){
    tabPanel(
      'ORA',
      sidebarLayout(
        
        # Sidebar panel for inputs ----
        sidebarPanel(
          
          selectInput(
            inputId = ns("de_direction"),
            label = 'Consider all peaks or only up/down-regulated peaks',
            multiple = FALSE,
            choices = c('Up','Down','Combined'),
            selected = 'Combined'
          ),
          # selectInput(
          #   inputId = ns("background_selector"),
          #   label = "Background space",
          #   multiple = FALSE,
          #   choices = c("Detected metabolome", "Whole metabolome"),
          #   selected = "Detected metabolome"
          # ),
          # add slider to select the minimum number of pathways to be considered before peak mapping
          sliderInput(
            inputId = ns("min_pathway_size"),
            label = "Discard pathways with overall size of less than x number of metabolites:",
            min = 1,
            max = 10,
            value = 3,
            step = 1
          ),
          # slider input for the number of hits in ORA to retain the pathway
          sliderInput(
            inputId = ns("min_pathway_hits"),
            label = "Minimum number of hits in a pathway",
            min = 1,
            max = 10,
            value = 2,
            step = 1
          ),
          # slider input for p-value cutoff for compound filtering for ORA
          sliderInput(
            inputId = ns("ora_pvalue_cutoff"),
            label = "P-value cutoff for pathway filtering",
            min = 0.01,
            max = 1,
            value = 0.05,
            step = 0.01
          ),
          # button to start the group comparison
          actionButton(
            inputId = ns("submit_from_ora"),
            label = "Submit",
            icon = icon("play")
          )
        ),
        
        #Main panel for displaying table of DE genes
        mainPanel(
          DT::dataTableOutput(ns('data'))
        )
        )
    )
  }else{
    NULL
  }
}

#' @rdname DEsummaryPanel
#' @export
BulkORAPanelServer <- function(id, bulk.expression.matrix, bulk.metadata, DEresults, anno){
  
  # check whether inputs (other than id) are reactive or not
  stopifnot({
    is.reactive(DEresults)
    is.reactive(bulk.expression.matrix)
    is.reactive(bulk.metadata)
    !is.reactive(anno)
  })
  
  moduleServer(id, function(input, output, session){
    
  get_ORA <- reactive({
    print('running ORA')
    execute_ora(de_peaks = DEresults()$DE()$DEtableSubset,path_dict = NULL,
                background = input[['background_selector']],
                min_path_size = input[['min_pathway_size']],
                ora_pvalue_cutoff = input[['ora_pvalue_cutoff']],
                min_pathway_hits = input[['min_pathway_hits']],
                peak_direction = input[['de_direction']])
  }) %>% bindEvent(input[["submit_from_ora"]])
  
  dataTable <- reactive({
    print(colnames(get_ORA()))
    get_ORA() |> select(-metabolites) |>
      DT::datatable() %>%
      DT::formatSignif(columns = c('Raw.p', 'Holm.p','FDR'), digits = 3)
  })
    
  output[['data']] <- DT::renderDataTable(dataTable())
  })
}

#DEsummaryPanelApp <- function(){
#  shinyApp(
#    ui = navbarPage("DE", tabPanel("", tabsetPanel(DEpanelUI('RNA'), DEsummaryPanelUI('RNA')))),
#    server = function(input, output, session){
#      DEresults <- DEpanelServer('RNA')
#      DEsummaryPanelServer('RNA', DEresults)
#    }
#  )
#}
