


##' Get differential peaks for a pixel neighbourhood
##'
##' For a given coordinate (x_tf, y_tf), compute differential peaks between the local neighbourhood and control samples using de_analysis.
##'
##' @param x_tf Numeric; x_tf-coordinate of the target spot.
##' @param y_tf Numeric; y_tf-coordinate of the target spot.
##' @param intensity.per.sample Matrix or data frame of intensities (spots x features) for the sample.
##' @param metadata.per.sample Data frame of spot metadata with x_tf, y_tf and spot_id columns.
##' @param control.matrix Matrix of control sample intensities (features x control spots).
##' @param min.neighbours Integer; minimum number of neighbouring spots required (default 3).
##' @param pvalue.cutoff Numeric; adjusted p-value cutoff for significance.
##' @param lfc.cutoff Numeric; log-fold-change cutoff for calling significance.
##' @param test Character; statistical test to use (default 't-test').
##' @param anno Data frame; annotation data for features used by de_analysis.
##' @return Data frame of significantly differential peaks (or NULL if neighbourhood too small).
##' @keywords pixel, differential, enrichment
#' @keywords internal
get_differential_peaks <- function(x_tf, y_tf, intensity.per.sample, metadata.per.sample, control.matrix, min.neighbours = 3, pvalue.cutoff = 0.05, lfc.cutoff = 0.5, test = 't-test', anno) {
  # Find the neighbours and check there are enough (gcd=1, use x_tf/y_tf)
  neighbours <- metadata.per.sample[
    abs(metadata.per.sample$x_tf - x_tf) <= 1 &
      abs(metadata.per.sample$y_tf - y_tf) <= 1,
  ]
  if (nrow(neighbours) >= min.neighbours) {
    intensity.sub <- intensity.per.sample[
      abs(metadata.per.sample$x_tf - x_tf) <= 1 &
        abs(metadata.per.sample$y_tf - y_tf) <= 1,
    ]
    rownames(intensity.sub) <- paste0('comparison_', 1:nrow(intensity.sub))
    intensity.sub <- t(intensity.sub)
    comparison.matrix <- cbind(control.matrix, intensity.sub)
    de.table <- de_analysis(
      intensity_matrix = comparison.matrix,
      condition = c(rep('control', ncol(control.matrix)), rep('comparison', ncol(intensity.sub))),
      var1 = 'control',
      var2 = 'comparison',
      test = test,
      anno = anno
    )
    de.table <- de.table[de.table$pvalAdj < pvalue.cutoff & abs(de.table$lfc) > lfc.cutoff, ]
    return(de.table)
  }
}

##' Get enriched pathways for a pixel
##'
##' Uses local differential peaks to run ORA and return pathway results for a given spot index (row) within the sample.
##'
##' @param row Integer; index (row number) within metadata.per.sample corresponding to the target spot.
##' @param intensity.per.sample Spot-by-feature intensity matrix for the sample.
##' @param metadata.per.sample Data frame of spot metadata for the sample (must contain x_tf, y_tf and spot_id).
##' @param control.table Control sample intensity matrix generated by make_control_samples.
##' @param min.neighbours Integer; minimum neighbours (unused but kept for API compatibility).
##' @param pvalue.cutoff Numeric; adjusted p-value cutoff for DE peaks.
##' @param lfc.cutoff Numeric; log-fold-change cutoff for DE peaks.
##' @param test Character; statistical test to use for DE.
##' @param background Optional background gene list for ORA.
##' @param min_path_size Integer; minimum pathway size to consider in ORA.
##' @param ora_pvalue_cutoff Numeric; ORA p-value cutoff.
##' @param min_pathway_hits Integer; minimum pathway hits.
##' @param gap Numeric; neighbourhood gap used to build the comparison set.
##' @param anno Data frame; annotation data used by ORA/DE.
##' @param organism Character or code used by pathway DB lookup.
##' @return Data frame of ORA results annotated with x and y coordinates, or NULL if no pathways found.
##' @keywords pixel, enrichment, ORA
get_enriched_pathways_perpixel <- function(
    row,
    intensity.per.sample,
    metadata.per.sample,
    control.table,
    min.neighbours = 3,
    pvalue.cutoff = 0.05,
    lfc.cutoff = 0.5,
    test = 't-test',
    background = NULL,
    min_path_size = 3,
    ora_pvalue_cutoff = 1.01,
    min_pathway_hits = 2, gap,
    anno,
    organism
) {
  de.table <- get_differential_peaks(
    metadata.per.sample[row, 'x_tf'],
    metadata.per.sample[row, 'y_tf'],
    intensity.per.sample,
    metadata.per.sample,
    control.table,
    min.neighbours = min.neighbours,
    pvalue.cutoff = pvalue.cutoff,
    lfc.cutoff = lfc.cutoff,
    test = test,
    anno = anno
  )
  current.row <- c(x_tf = metadata.per.sample[row, 'x_tf'], y_tf = metadata.per.sample[row, 'y_tf'], 'significant' = if (!is.null(de.table)) paste(de.table$m_z, collapse = ',') else NA)
  if (!is.null(de.table)) {
    ora <- execute_ora(
      de_peaks = de.table,
      path_dict = NULL,
      background = background,
      min_path_size = min_path_size,
      ora_pvalue_cutoff = ora_pvalue_cutoff,
      min_pathway_hits = min_pathway_hits,
      organism = organism,
      anno = anno,
      kegg_db = kegg_db
    )
    if (!is.null(ora)) {
      if (nrow(ora) != 0) {
        ora$x_tf <- metadata.per.sample[row, 'x_tf']
        ora$y_tf <- metadata.per.sample[row, 'y_tf']
        return(ora)
      } else {
        return(NULL)
      }
    } else {
      return(NULL)
    }
  }
}

##' Run pixel-level enrichment pipeline in parallel
##'
##' Iterates over samples and computes per-spot ORA results in parallel. Returns a named list of per-sample ORA result data frames.
##'
##' @param intensity.matrix Spot-by-feature intensity matrix (all samples concatenated).
##' @param bulk.intensity.matrix Feature-by-sample matrix used to build control sets.
##' @param metadata Data frame of per-spot metadata containing Sample and spot_id columns.
##' @param anno Data frame; annotation data for features used by de_analysis.
##' @param control.samples Character vector of sample IDs to use as controls.
##' @param min.neighbours Integer; minimum neighbours (unused but retained for compatibility).
##' @param pvalue.cutoff Numeric; DE adjusted p-value cutoff.
##' @param lfc.cutoff Numeric; log fold-change cutoff.
##' @param test Character; statistical test to use for de_analysis.
##' @param background Optional background gene list for ORA.
##' @param min_path_size Integer; minimum ORA pathway size.
##' @param ora_pvalue_cutoff Numeric; ORA p-value cutoff.
##' @param min_pathway_hits Integer; minimum pathway hits required.
##' @param ncores Integer; number of cores for parallel execution.
##' @param organism Character; organism code for pathway lookup.
##' @return Named list where each element is a data frame of ORA results for a sample.
##' @keywords pixel, enrichment, parallel

run_pixellevel_pipeline_parallel <- function(
  intensity.matrix,
  bulk.intensity.matrix,
  metadata,
  anno,
  control.samples,
  comparison.samples,
  min.neighbours = 3,
  pvalue.cutoff = 0.05,
  lfc.cutoff = 0.5,
  test = 't-test',
  background = NULL,
  min_path_size = 3,
  ora_pvalue_cutoff = 1.01,
  min_pathway_hits = 2,
  ncores = 1,
  organism = 'Human'
) {

  anno_sub = anno[!is.na(anno$name),]
  control.matrix <- bulk.intensity.matrix[anno_sub$m_z, control.samples, drop = FALSE]

listofoutputs <- list()
message('Starting pixel-level enrichment pipeline')
for (sample in comparison.samples) {
  message(paste0('Processing sample: ', sample))
  intensity.sub <- intensity.matrix[metadata$Sample == sample, ]
  metadata.sub <- metadata[metadata$Sample == sample, ]

  if (ncores > 1) {
      message(paste0("Running pixel-level enrichment for sample ", sample, " in parallel using ", ncores, " cores..."))
      cl <- parallel::makeCluster(ncores)
      parallel::clusterExport(
        cl,
        c(
          "get_differential_peaks", "execute_ora", "metadata.sub", "control.matrix", "de_analysis",
          "get_enriched_pathways_perpixel", "anno", "organism", "run_ORA","kegg_db", "intensity.sub"
        ),
        envir = environment()
      )
      outlist <- pbapply::pblapply(
        seq_len(nrow(metadata.sub)),
        FUN = function(x) get_enriched_pathways_perpixel(
          x,
          intensity.per.sample = intensity.sub,
          metadata.per.sample = metadata.sub,
          control.table = control.matrix,
          min.neighbours = 3,
          pvalue.cutoff = 0.05,
          lfc.cutoff = 0.5,
          test = 't-test',
          background = NULL,
          min_path_size = 3,
          ora_pvalue_cutoff = 1.01,
          min_pathway_hits = 2,
          anno = anno,
          organism = organism
        ),
        cl = cl
      )
      names(outlist) <- metadata.sub$pixel_id
      outlist <- outlist[!sapply(outlist, is.null)]
      outdf <- dplyr::bind_rows(outlist, .id = "pixel_id")
      outdf <- merge(outdf, metadata.sub)
      parallel::stopCluster(cl)
      listofoutputs[[sample]] <- outdf
  } else {
      message(paste0("Running pixel-level enrichment for sample ", sample, " sequentially..."))
            outlist <- pbapply::pblapply(
              seq_len(nrow(metadata.sub)),
              FUN = function(x) get_enriched_pathways_perpixel(
                x,
                intensity.per.sample = intensity.sub,
                metadata.per.sample = metadata.sub,
                control.table = control.matrix,
                min.neighbours = 3,
                pvalue.cutoff = 0.05,
                lfc.cutoff = 0.5,
                test = 't-test',
                background = NULL,
                min_path_size = 3,
                ora_pvalue_cutoff = 1.01,
                min_pathway_hits = 2,
                anno = anno,
                organism = organism
              )
            )
            names(outlist) <- metadata.sub$pixel_id
            outlist <- outlist[!sapply(outlist, is.null)]
            outdf <- dplyr::bind_rows(outlist, .id = "pixel_id")
            outdf <- merge(outdf, metadata.sub)
            listofoutputs[[sample]] <- outdf
  }
}
  return(listofoutputs)
}





